### ISSUE TITLE
Windows 2008 R2 Support

### ISSUE THREAD

**Issue by bmurtagh** [dev-sec/ansible-windows-hardening#4]
Hello,

My apologies to resorting to using a GitHub Issue to ask this question, but I'm couldn't find another method to contact the maintainers. 

I am trying to find out if the Ansible, Chef, or Puppet versions support Windows Server 2008 R2. I completely understand it's EOL, etc. but we have legacy software that requires that operating system.
 
Any help is appreciate.

**Comment by rndmh3ro** [comment]
Hey @bmurtagh,

no, we don't suppoer 2008 R2 anymore.
